DROP TABLE IF EXISTS Units CASCADE;
CREATE TABLE Units (
  UnitID INT PRIMARY KEY,
  UnitName VARCHAR(100) NOT NULL,
  BaseLocation VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS Shul CASCADE;
CREATE TABLE Shul (
  ShulID INT PRIMARY KEY,
  Capacity INT NOT NULL,
  PrayerTimes VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS located_in CASCADE;
CREATE TABLE located_in (
  UnitID INT NOT NULL,
  ShulID INT NOT NULL,
  PRIMARY KEY (UnitID, ShulID),
  FOREIGN KEY (UnitID) REFERENCES Units(UnitID),
  FOREIGN KEY (ShulID) REFERENCES Shul(ShulID)
);

DROP TABLE IF EXISTS Soldiers CASCADE;
CREATE TABLE Soldiers (
  SoldierID INT PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Rank VARCHAR(30) NOT NULL,
  Role VARCHAR(30) NOT NULL,
  ShulID INT NOT NULL,
  FOREIGN KEY (ShulID) REFERENCES Shul(ShulID)
);

DROP TABLE IF EXISTS Events CASCADE;
CREATE TABLE Events (
  EventID INT PRIMARY KEY,
  EventName VARCHAR(100) NOT NULL,
  EventDate DATE NOT NULL,
  Location VARCHAR(100) NOT NULL,
  SoldierID INT NOT NULL,
  ShulID INT NOT NULL,
  FOREIGN KEY (SoldierID) REFERENCES Soldiers(SoldierID),
  FOREIGN KEY (ShulID) REFERENCES Shul(ShulID)
);

DROP TABLE IF EXISTS ReligiousEquipment CASCADE;
CREATE TABLE ReligiousEquipment (
  EquipmentID INT PRIMARY KEY,
  EquipmentName VARCHAR(100) NOT NULL,
  Quantity INT NOT NULL,
  StorageLocation VARCHAR(100) NOT NULL,
  ShulID INT NOT NULL,
  EventID INT,
  FOREIGN KEY (ShulID) REFERENCES Shul(ShulID),
  FOREIGN KEY (EventID) REFERENCES Events(EventID)
);

DROP TABLE IF EXISTS HalachicGuidelines CASCADE;
CREATE TABLE HalachicGuidelines (
  GuidelineID INT PRIMARY KEY,
  Title VARCHAR(100) NOT NULL,
  Description VARCHAR(500) NOT NULL,
  DateIssued DATE NOT NULL,
  SoldierID INT NOT NULL,
  FOREIGN KEY (SoldierID) REFERENCES Soldiers(SoldierID)
);