DROP TABLE IF EXISTS ReligiousEquipment;
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS HalachicGuidelines;
DROP TABLE IF EXISTS located_in;
DROP TABLE IF EXISTS Soldiers;
DROP TABLE IF EXISTS Shul;
DROP TABLE IF EXISTS Units;
